const FETCH_MOVIES_START  = 'FETCH_MOVIES_START'
const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS'
const FETCH_MOVIES_FAILURE = 'FETCH_MOVIES_FAILURE'
const HANDLE_QUERY_CHANGE = 'HANDLE_QUERY_CHANGE'

export {FETCH_MOVIES_START, FETCH_MOVIES_SUCCESS,
     FETCH_MOVIES_FAILURE, HANDLE_QUERY_CHANGE}

